### PR TITLE
dependabot - only security updates

### PR DESCRIPTION
**Pull request by BaderBC**
image

The only reason to update libraries in our situation is to avoid using deprecated or vulnerable dependencies.
I don't like idea of that many (10) useless pull requests.

### CODE REVIEW

**Comment by maxidragon** [comment]
I'm not 100% sure, but this probably won't work. You are blocking **all** dependabot PR's, including security updates. Instead, we should delete `dependabot.yml` file and enable security updates in repository settings

**Review by maxidragon — COMMENTED** [review]
I'm not 100% sure, but this probably won't work. You are blocking **all** dependabot PR's, including security updates. Instead, we should delete `dependabot.yml` file and enable security updates in repository settings

**Review by cooligus — APPROVED** [review]
Let's try then

**Review by cooligus — CHANGES_REQUESTED** [review]
Nevermind @maxidragon knew what he said
image

**Review by maxidragon — APPROVED** [review]

**Pull request merged**
