### PR TITLE
Create auto-approve.yml

### PR DESCRIPTION
**Pull request by cooligus**

### CODE REVIEW

**Comment by maxidragon** [comment]
I think it's not a good idea to have something like this, dependencies updates should be reviewed manually

**Comment by cooligus** [comment]
But it's extremely annoying that you have 99 PR per day

**Comment by maxidragon** [comment]
Yes, but you can check if the dependency update didn't break anything

**Comment by cooligus** [comment]
You can, but you don't

**Comment by BaderBC** [comment]
It sound like a good idea but firstly we need to have 100% tests coverage

**Pull request closed without merging**
